package SDCS;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Zifan
 */
public class Add_New_Project extends javax.swing.JFrame {

    /**
     * Creates new form Add_New_Client
     */
    public Add_New_Project() {
        initComponents();
       
         teamid();
          
    }
 
       private void id() {

        try {
            //database connection
            DConnection c = new DConnection();

            String str = "SELECT * FROM project";
            ResultSet rs = c.s.executeQuery(str);
            if (!rs.next()) {
                pid.setText("1");
            } else {
                String str1 = "SELECT count(ClientID) AS IDC  FROM client";
                ResultSet result2 = c.s.executeQuery(str1);
                if (result2.next()) {
                    int id = result2.getInt("IDC") + 1;
                    String ss = String.valueOf(id);
                    pid.setText(ss);
                                    }
                else {
                    System.out.println("OOOOO");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
       }
    
        private void clear(){
       // Aname.requestFocus();
        ptitle1.setText("");
          adate.setCalendar(null);
           preq.setText("");
             sdate.setCalendar(null);
               pamount.setText("");
                pid.setText("");
           }
       
    
    public void teamid()
       {
            DConnection c = new DConnection();
          
          try{
               String str = "SELECT TeamID FROM projectteam where status='available'";
               ResultSet rs = c.s.executeQuery(str);
               while(rs.next())
               {
                   ctid.addItem(rs.getString("TeamID"));
               }
              
          }
          catch(Exception e)
          {
              
          }
       }
           
           
    public void table() {
        // TODO add your handling code here:
        try {
            //database connection
            DConnection c = new DConnection();
            String str = "SELECT  ClientID,Name,Admission_Date, Project_Type FROM client;";
            ResultSet rs = c.s.executeQuery(str);
            cinfo1.setModel(DbUtils.resultSetToTableModel(rs));   //employee table show
        } catch (Exception e) {
            System.out.println(e);
        }
    }
     public void table1() {
        // TODO add your handling code here:
        try {
            //database connection
            DConnection c = new DConnection();
            String str = "SELECT * FROM projectteam;";
            ResultSet rs = c.s.executeQuery(str);
            tinfo.setModel(DbUtils.resultSetToTableModel(rs));   //employee table show
        } catch (Exception e) {
            System.out.println(e);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        cname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        ccid = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        preq = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        sdate = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cadd = new javax.swing.JTextArea();
        cemail = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        pamount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tinfo = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        ptitle1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pmid = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ctid = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        cinfo1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save.png"))); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, -1, 29));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reset_20px.png"))); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, 100, 29));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit application.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, 100, 29));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 505, 700, 0));
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 240, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Project Accept date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));
        getContentPane().add(adate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 240, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        ccid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccidActionPerformed(evt);
            }
        });
        getContentPane().add(ccid, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 70, 30));

        preq.setColumns(20);
        preq.setRows(5);
        jScrollPane2.setViewportView(preq);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 240, 79));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Project Submit date");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));
        getContentPane().add(sdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 240, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Project ID");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 240, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Project Requirements");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search1.png"))); // NOI18N
        jButton4.setText(" Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, 30));

        cadd.setColumns(20);
        cadd.setRows(5);
        jScrollPane1.setViewportView(cadd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 240, 79));

        cemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemailActionPerformed(evt);
            }
        });
        getContentPane().add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 240, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1100, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 122, 770, 0));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Project Title");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        pamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pamountActionPerformed(evt);
            }
        });
        getContentPane().add(pamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 240, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Client ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 618, 1100, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1100, 10));

        tinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tinfo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 610, 200));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("TeamID");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        ptitle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptitle1ActionPerformed(evt);
            }
        });
        getContentPane().add(ptitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 240, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Project Manager ID");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        pmid.setEditable(false);
        pmid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmidActionPerformed(evt);
            }
        });
        getContentPane().add(pmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 240, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Amount");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        getContentPane().add(ctid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 100, -1));

        cinfo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(cinfo1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 610, 190));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Add New Project");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/new porject.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String pid2 = pid.getText();
        String cid = ccid.getText();
       String pmid1 = pmid.getText();
        String teamid = (String) ctid.getSelectedItem();
      String ptitle = ptitle1.getText();
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String accdate = sdf.format(adate.getDate());
       String prequ = preq.getText();
        String subdate = sdf.format(sdate.getDate());
         String pam = pamount.getText();
         
            //database connection
        DConnection c = new DConnection();
        
        try{
                 String str="INSERT INTO project(ProjectID,title,AcceptDate,Project_Requirements,SubmitDate,Amount,ClientID, PMID, TeamID) VALUES ('"+pid2+"','"+ptitle+"','"+accdate+"','"+prequ+"','"+subdate+"','"+pam+"','"+cid+"','"+pmid1+"','"+teamid+"')";
                String str1="UPDATE projectteam SET Status='working' WHERE TeamID='"+teamid+"'";
                 c.s.executeUpdate(str);
                 c.s.executeUpdate(str1);
            JOptionPane.showMessageDialog(null, "New Client Project Added");
            clear();
            table1();
          //  id();
        }
        catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Can't Added! Please Check All Details"); 
        } 

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         // TODO add your handling code here:

      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "You Really want to Exit ", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cemailActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
               String st = ccid.getText();
        //database connection
        DConnection c = new DConnection();

        try {
            String str = "select * from client where ClientID = '" + st + "'";
            ResultSet rs = c.s.executeQuery(str);

            while (rs.next()) {

                //name,Tel,gender,age, NIC,Emp_Type,salary,Joined_Date, username, password
                
                cname.setText(rs.getString("Name"));
                  cemail.setText(rs.getString("Email"));
                     cadd.setText(rs.getString("Age"));
                     pmid.setText(rs.getString("Emp_ID"));

                
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void pamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pamountActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        table();
        table1();
        
        
        
    }//GEN-LAST:event_formComponentShown

    private void ptitle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptitle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptitle1ActionPerformed

    private void pmidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmidActionPerformed

    private void ccidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccidActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_New_Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser adate;
    private javax.swing.JTextArea cadd;
    private javax.swing.JTextField ccid;
    private javax.swing.JTextField cemail;
    private javax.swing.JTable cinfo1;
    private javax.swing.JTextField cname;
    private javax.swing.JComboBox<String> ctid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField pamount;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pmid;
    private javax.swing.JTextArea preq;
    private javax.swing.JTextField ptitle1;
    private com.toedter.calendar.JDateChooser sdate;
    private javax.swing.JTable tinfo;
    // End of variables declaration//GEN-END:variables

}
